idealista/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.views.generic.base import RedirectView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
   url(r'^',include(('idealista_app.urls','idealista_app'),namespace='idealista_app')),
    url(r'^$',RedirectView.as_view(url="/home/"))
]

idealista_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    url(
        regex=r'^register/$',
        view=views.register_user,
        name='register_user'
    ),
    url(
        regex=r'^home/$',
        view=views.homePage,
        name='homePage'
    ),
    url(
        regex=r'^submit/$',
        view=views.submit,
        name='submit'
    ),
    url(
        regex=r'^login/',
        view=views.login,
        name='login'
    ),
    url(
        regex=r'^logout/',
        view=views.logout,
        name='logout'
    ),
    url(
        regex=r'^publicar-anuncio/',
        view=views.publicarAnuncio,
        name='publicarAnuncio'
    ),
    url(
        regex=r'^profile/',
        view=views.profile,
        name='profile'
    ),
    url(
        regex=r'^myposts',
        view=views.myposts,
        name='myposts'
    ),

    url(
        regex=r'^quienessomos',
        view=views.quienessomos,
        name='quienessomos'

    ),
  
    path(r'posts/<slug:operation>/<slug:type>/<state>/', views.posts, name='posts'),
    path(r'posts/<slug:operation>/<slug:type>/<state>/<province>/', views.posts, name='posts'),
    path(r'posts/<slug:operation>/<slug:type>/<state>/<province>/<location>/', views.posts, name='posts'),
    path(r'placeholder/<id>/', views.placeholder, name='placeholder'),

]

idealista_app/forms.py
from django import forms
from django.contrib.auth.models import User

from .dummies import add_user, user_exists
from .models import *
from cloudinary.forms import CloudinaryJsFileField, CloudinaryUnsignedJsFileField
from cloudinary.compat import to_bytes
import cloudinary, hashlib


class LoginForm(forms.Form):
    username = forms.EmailField(label='Email de acceso')
    password = forms.CharField(
        widget=forms.PasswordInput, label='Tu contraseña')
    remember = forms.BooleanField(label='Recordar tus datos', required=False)


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(
        widget=forms.PasswordInput, label='Contraseña actual')
    new_password = forms.CharField(
        widget=forms.PasswordInput, label='Nueva contraseña',
        help_text="Utiliza al menos 4 caracteres, letras y números")
    repeat_password = forms.CharField(
        widget=forms.PasswordInput, label='Vuelve a escribir la nueva contraseña')
    remember = forms.BooleanField(
        label="Recuérdame en este dispositivo", required=False)

    def validate(self, value):
        """Check if value consists only of valid emails."""
        # Use the parent's handling of required fields, etc.
        super().validate(value)
        np = self.cleaned_data.get('new_password')
        rp = self.cleaned_data.get('repeat_password')
        if np != rp:
            raise forms.ValidationError('Las contraseñas no coinciden.')
        self.validate_email(value.email)


class RegisterForm(forms.Form):
    email = forms.EmailField(label='Email de acceso')
    name = forms.CharField(label='Nombre')
    password = forms.CharField(
        widget=forms.PasswordInput, label='Tu contraseña')
    aceptar_privacidad = forms.BooleanField(
        label='Aceptar la política de privacidad')
    recibir_info = forms.BooleanField(label="""
        Recibir información de inmuebles,
        noticias y otras comunicaciones
        promocionales desde idealista,
        idealista/data, idealista/hipotecas o
        Rentalia basadas en tu perfil.""", required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(RegisterForm, self).__init__(*args, **kwargs)

    def validate(self, value):
        """Check if value consists only of valid emails."""
        # Use the parent's handling of required fields, etc.
        super().validate(value)
        self.validate_email(value.email)

    def clean_email(self):
        email = self.cleaned_data['email']

        try:
            match = User.objects.get(email=email)
        except User.DoesNotExist:
            # Unable to find a user, this is fine
            return email
        raise forms.ValidationError('Este email ya está registrado.')

    def save(self, commit=True):

        # using email as username
        email = self.cleaned_data.get('email')
        name = self.cleaned_data.get('name')
        raw_password = self.cleaned_data.get('password')
        recibir_info = self.cleaned_data.get('recibir_info')

        user = User.objects.create_user(
            email, email, raw_password, first_name=name
        )
        user.save()


class PropertyForm(forms.Form):
    # property type

    pro_type = forms.ChoiceField(
        label='Tipo de inmueble', choices=[])

    name = forms.CharField(label='Nombre*')

    op_type = forms.ChoiceField(
        label='Operación', choices=[])
    description = forms.CharField(label="Descripción*", widget=forms.Textarea)
    address = forms.CharField(label="Dirección*")
    address_number = forms.CharField(label='Número*', max_length=5)

    floor = forms.CharField(label='Piso', max_length=15, required=False)
    door = forms.CharField(label='Puerta', max_length=15, required=False)
    m_built = forms.DecimalField(
        label='Metros construidos*', max_digits=15, decimal_places=2)
    m_use = forms.DecimalField(
        label='Metros útiles*', max_digits=15, decimal_places=2)

    bath = forms.IntegerField(label='Numero de baños*')
    rooms = forms.IntegerField(label='Numero de habitaciones*')
    is_exterior = forms.BooleanField(label='Es exterior?', required=False)
    has_elevator = forms.BooleanField(label='Tiene ascensor?', required=False)
    price = forms.DecimalField(label='Precio*')

    state = forms.ChoiceField(label='Comunidad*', choices=[])
    province = forms.ChoiceField(label='Provincia*', choices=[])
    city = forms.ChoiceField(label='Ciudad*', choices=[])

    phone = forms.IntegerField(
        label='Número de teléfono*', max_value=999999999, min_value=600000000)

    photo = forms.ImageField(label="Foto del inmueble", required=False)

    # user

    def __init__(self, user, *args, **kwargs):
        super(PropertyForm, self).__init__(*args, **kwargs)
        self.user = user
        self.fields['op_type'].choices = [
            (p, p.name) for p in OperationType.objects.all()]
        self.fields['pro_type'].choices = [
            (p, p.name) for p in PropertyType.objects.all()]
        self.fields['state'].choices = [(c, c.name)
                                        for c in State.objects.all()]
        self.fields['province'].choices = [(':'.join([c.state.name, c.name]), c.name)
                                           for c in Province.objects.all()]
        self.fields['city'].choices = [(':'.join([c.province.name, c.name]), c.name)
                                       for c in Location.objects.all()]

    def clean_city(self):
        email = self.cleaned_data['city']

        try:
            return email.split(':')[1]
        except IndexError:
            # Unable to find a user, this is fine
            raise forms.ValidationError('Este email ya está registrado.')

    def save(self, commit=True):
        op_type_value = self.cleaned_data.get("op_type")
        op_type = OperationType.objects.filter(name=op_type_value).first()
        pro_type_value = self.cleaned_data.get("pro_type")
        pro_type = PropertyType.objects.filter(name=pro_type_value).first()
        # state_value = self.cleaned_data.get("state")
        # state = State.objects.filter(name=state_value).first()
        # province_value = self.cleaned_data.get("province")
        # province = Province.objects.filter(name=province_value).first()
        city_value = self.cleaned_data.get("city")
        city = Location.objects.filter(name=city_value).first()
        out = self.cleaned_data.copy()
        out['op_type'] = op_type
        out['pro_type'] = pro_type
        del out['state']
        del out['province']
        # del out['photo']  # TODO
        out['city'] = city
        out['user'] = self.user
        p = Property.objects.create(**out)
        p.save()

idealista_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .models import OperationType, PropertyType, State, Province, Location, Property, PropertyPics

from .forms import LoginForm, RegisterForm, ChangePasswordForm, PropertyForm

# from slugify import slugify

from .dummies import add_user, users


# Create your views here.


def placeholder(request, id=""):
    if request.method == 'GET':
        property = Property.objects.get(
                    id__icontains=id)
        context = {
            'property': property,
        }
        return render(request, 'idealista_app/placeholder.html', context)
    else:
        homePage(request)


def register_user(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user = auth.authenticate(
                username=form.cleaned_data.get('email'),
                password=form.cleaned_data.get('password'))
            if user is not None and user.is_active:
                auth.login(request, user)
                return redirect('idealista_app:homePage')
            else:
                return HttpResponseRedirect('idealista_app:register_user')
    else:
        form = RegisterForm()
    return render(request, 'idealista_app/register.html', {'form': form})


def get_posts(request, operation, type, state):
    if state:
        state = State.objects.get(name=state)
        type = PropertyType.objects.get(name=type)
        operation = OperationType.objects.get(name=operation)
        # t = PropertyType.objects.filter(name=type).first()
        ads = Property.objects.filter(
            op_type=operation, pro_type=type, city__province__state=state)
        locations = Province.objects.filter(state=state)
        path = '/'.join([operation.acr, type.acr, state.acr])

        context = {
            'posts': ads,
            'locations': locations,
            'level': state,
            'path': path,
        }
        return render(request, 'idealista_app/buscar-publicaciones.html', context)


def homePage(request):

    if request.method == 'GET':
        type_operation = OperationType.objects.filter(id__gt=0)
        type_properties = PropertyType.objects.filter(id__gt=0)
        states = State.objects.filter(id__gt=0)
        context = {
            'type_operations': type_operation,
            'type_properties': type_properties,
            'states': states,
        }
        return render(request, 'idealista_app/home.html', context)
    elif request.method == 'POST':
        return get_posts(request, operation=request.POST['op'], type=request.POST['tipo'], state=request.POST['comunidad'])


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def submit(request):
    return render(request, 'idealista_app/submit.html')


@login_required
def publicarAnuncio(request):

    """
    # Cloudinary -------------------------------------------------------------------------------------------------------
    unsigned = request.GET.get("unsigned") == "true"
    if (unsigned):
        try:
            api.upload_preset(PhotoUnsignedDirectForm.upload_preset_name)
        except api.NotFound:
            api.create_upload_preset(name=PhotoUnsignedDirectForm.upload_preset_name, unsigned=True,
                                     folder="preset_folder")

    direct_form = PhotoUnsignedDirectForm() if unsigned else PhotoDirectForm()
    context = dict(
        # Form demonstrating backend upload
        backend_form=PropertyForm(),
        # Form demonstrating direct upload
        direct_form=direct_form,
        # Should the upload form be unsigned
        unsigned=unsigned,
    )
    # When using direct upload - the following call is necessary to update the
    # form's callback url
    cl_init_js_callbacks(context['direct_form'], request)

     Cloudinary END ---------------------------------------------------------------------------------------------------
    """

    if request.method == 'POST':
        form = PropertyForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('idealista_app:homePage')
        else:
            pass  # print(form.errors)
    else:
        form = PropertyForm(request.user)
    return render(request, 'idealista_app/publicar-anuncio.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = auth.authenticate(
                username=form.cleaned_data.get('username'),
                password=form.cleaned_data.get('password'))
            if user is not None and user.is_active:
                auth.login(request, user)
                return redirect('idealista_app:homePage')
            else:
                return HttpResponseRedirect('idealista_app:login')
    else:
        form = LoginForm()

    return render(request, 'idealista_app/login.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'idealista_app/profile/profile.html')


@login_required
def myposts(request):
    if request.method == 'GET':
        user = request.user.id
        '''print(user)
        print(Property.objects.filter(user=user).values('city__name').select_related)'''
        properties_user = Property.objects.filter(user=user)
        context = {
            'properties_user': properties_user,
        }
        return render(request, 'idealista_app/profile/tus-anuncios.html', context)
    elif request.method == 'POST':
        Property.objects.get(id=request.POST['deletePost']).delete()
        user = request.user.id
        properties_user = Property.objects.filter(user=user)
        context = {
            'properties_user': properties_user,
        }
        return render(request, 'idealista_app/profile/tus-anuncios.html', context)
    else:
        return render(request, 'idealista_app/profile/profile.html')


def buscar_post(request):
    print('aaa')
    return render(request, 'idealista_app/profile/profile.html')


def posts(request, operation="", type="", state="", province="", location=""):
    if request.method == 'GET':
        if state:
            ads = ""
            locations = ""
            level = ""
            path = operation + '/' + type + '/' + state
            if province:
                path += '/'+province
                if location:
                    ads = Property.objects.filter(
                        op_type__acr=operation, pro_type__acr=type, city__acr=location)
                    level = Location.objects.get(acr=location)
                    path += '/'+location
                else:
                    ads = Property.objects.filter(
                        op_type__acr=operation, pro_type__acr=type, city__province__acr=province)
                    locations = Location.objects.filter(province__acr=province)
                    level = Province.objects.get(acr=province)
            else:
                ads = Property.objects.filter(
                    op_type__acr=operation, pro_type__acr=type, city__province__state__acr=state)
                locations = Province.objects.filter(state__acr=state)
                level = State.objects.get(acr=state)
        else:
            ads = Property.objects.all()
            locations = State.objects.all()
        context = {
            'posts': ads,
            'locations': locations,
            'level': level,
            'path': path,
        }
        return render(request, 'idealista_app/buscar-publicaciones.html', context)
    else:
        homePage(request)

def quienessomos(request):
      return render(request,'idealista_app/quienesSomos.html')


# l=[]
# propietat= objects.filter(propietat)
# for p in propietat:
    # foto = objects.filter(propierty=p)
    # t (p, foto)
    # l.append(t)
# context =

templates/idealista_app/base.html
<html>

<head>
    <meta charset="utf-8">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/8593a80e63.js" crossorigin="anonymous"></script>
</head>

<body style="padding-top: 65px;">
    <!-- Only god knows why 65px padding is required -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand" href="{% url 'idealista_app:homePage' %}">
            <img src="{% static "img/logo.svg" %}" width="200" height="30" class="d-inline-block align-top"
                alt="oportunista">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav ml-auto">
                <a href="{% url 'idealista_app:publicarAnuncio' %}" class="btn btn-outline-secondary rounded text-black">
                    <small>
                        <i class="fas fa-thumbtack"></i>
                        Pon tu anuncio gratis
                    </small>
                </a>
            
                <li class="nav-item active" href="#">
                    <a class="nav-link" href="{% url 'idealista_app:myposts' %}">Tus posts</a>
                </li>
                <!-- li class="nav-item" href="#">
                    <a class="nav-link" href="#">Tus búsquedas</a>
                </li -->
                <li class="nav-item" href="#">

                    <a class="nav-link" href="{% url 'idealista_app:profile' %}"><i class="fas fa-user-circle"></i> {{ user.first_name }}</a>
                </li>
            </ul>

        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <footer id="footer" class="container-fluid bg-light">
        <div class="row py-3">
            <img src="{% static "img/logo.svg" %}" width="300" height="60" class="d-inline-block  align-top"
                alt="oportunista">
        </div>
        <div class="row" style="text-align: center;">
            <div class="col">

                <p class="text-muted">
                    <b>Sobre oportunista</b>
                </p>

                <ul class="list-unstyled">
                    <li><a href="{% url 'idealista_app:quienessomos' %}" class="text-info"> Quiénes somos</a></li>
                  
                </ul>

            </div>
            
        </div>
        </div>
        <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="{% static "js/bootstrap.js" %}"></script>
        {% block script %}
        {% endblock %}
</body>

</html>

templates/idealista_app/home.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://kit.fontawesome.com/8593a80e63.js" crossorigin="anonymous"></script>
</head>

<body>
  <nav class="bg bg-idealista navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'idealista_app:homePage' %}">
      <img src="{% static "img/logo.svg" %}" width="300" height="50" class="d-inline-block align-top" alt="Responsive image">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
      aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <a href="{% url 'idealista_app:publicarAnuncio' %}" class="btn btn-outline-secondary rounded text-black">
          <small>
            <i class="fas fa-thumbtack"></i>
            Pon tu anuncio gratis
          </small>
        </a>
        {% endif %}
        <li class="nav-item active" href="#">
          {% if user.is_authenticated %}
          <a href="{% url 'idealista_app:logout' %}">
            <button class="btn"><i class="fa fa-user text-secondary"></i>
              <small>
                Cerrar sesión
              </small>
            </button>
          </a>
          {% else %}
          <a href="{% url 'idealista_app:login' %}">
            <button class="btn"><i class="fa fa-user text-secondary"></i>
              <small>
                Acceso Usuarios
              </small>
            </button>
          </a>
          {% endif %}
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item" href="#">
          <select class="form-control">
            <option data-content='<span class="flag-icon flag-icon-us"></span> Español'>Español</option>
          </select>
        </li>
        {% endif %}

        {% if  user.is_authenticated %}
        <li class="nav-item active">
          <a href="{% url 'idealista_app:profile' %}">
            <button class="btn">
              <i class="fas fa-user-circle text-primary fa-2x"></i>
              <small>{{ user.first_name }}</small>
            </button>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

    <div style="background:  no-repeat center top url({% static "img/casaBackground.jpg" %}) ;">
  <div class=" container max-width-540 py-5">

    <form class="bg-primary px-2" action="{% url 'idealista_app:homePage' %}" method="POST">
      {% csrf_token %}
      <div class="row pt-3 px-2 justify-content-center">
        <h2>Haz caso a tu intuición</h2>
      </div>

      <div class="form-row">
        <div class="col">
          <select id="op" name="op" class="custom-select rounded-0" multiple style="height: 240px;">
            {% for type in type_operations %}
            <option>{{type.name}}</option>
            {% endfor %}
          </select>
        </div>

        <div class="col">
          <select id="tipo" name="tipo" class="custom-select rounded-0" multiple style="height: 240px;">
            {% for type in type_properties %}
            <option>{{type.name}}</option>
            {% endfor %}
          </select>
        </div>

        <div class="col">

          <select id="comunidad" name="comunidad" class="custom-select rounded-0" multiple style="height: 240px;">
            {% for state in states %}
            <option>{{state.name}}</option>
            {% endfor %}
          </select>
        </div>

      </div>

      <div class="form-row py-2 px-1 justify-content-end">
        <div class="col-4"><input class="btn btn-secondary btn-block rounded-0" type="submit" value="Buscar"></div>

      </div>
    </form>

    <!--div class="row">

        <div class="col">
          <select id="primer" class="custom-select rounded-0" multiple style="height: 240px;">
            {% for type in type_operations %}
            <option>{{type.name}}</option>
            {% endfor %}
          </select>
        </div>

        <div class="col">

          <select id="segon" class="custom-select rounded-0" multiple style="height: 240px;">
            {% for type in type_properties %}
            <option>{{type.name}}</option>
            {% endfor %}
          </select>
        </div>

        <div class="col">

          <select id="tercer" class="custom-select rounded-0" multiple style="height: 240px;">
            {% for state in states %}
            <option>{{state.name}}</option>
            {% endfor %}
          </select>
        </div>
      </div -->


    <!--div class="row py-2 px-1 justify-content-end">
        <div class="col-4">

          <a class="btn btn-secondary btn-block rounded-0" type="submit" onclick="redirect(this)">

            <strong>
              Buscar
            </strong>
          </a>
        </div>

      </div-->

    </form>
    <br>
    <br>
    <br>
    <br>
    <br>
   
    <div class="bg bg-light row py-5 px-3">
      <div class="col-6">
        <div class="row">
          <h5> <strong>Poner tu anuncio es gratis...</strong></h5>
        </div>

      </div>
      <div class="col-4">
        <div class="row">
          <a class="btn btn-secondary btn-block rounded-0" href="{% url 'idealista_app:publicarAnuncio' %}">
         
            <strong>Poner anuncio</strong>
       
        </a>
        </div>

      </div>
     
    </div>

    <!-- not so secret secrets 
    <div class="bg bg-light row py-2 px-3">
      <form id="busqueda">
        <div class="row">
          <div class="col">
            <h5> <strong>Búsqueda por texto libre</strong></h5>
          </div>
        </div>

        <div class="row justify-content-start">
          {% for type in type_properties %}
          <div class="form-group col-auto">
            <input type="radio" name="radio-compartir" value="bool">
            <label class="form-check-label" for="radio-compartir">
              {{type.name}}
            </label>
          </div>
          {% endfor %}
        </div>

        <form>



          <div class="row">
            <div class="col-4">
              <select class="form-control">
                <option>Selecciona...</option>
                <option>Obra nueva</option>
                <option>Viviendas</option>
                <option>Habitación</option>
                <option>Oficinas</option>
                <option>Locales o naves</option>
                <option>Garajes</option>
                <option>Trasteros</option>
                <option>Edificios</option>
                <option>Terrenos</option>
              </select>
            </div>

            <div class="col-6">
              <input type="text" class="form-control" id="location" aria-describedby="locationHelp"
                placeholder="Escribe dónde buscas">
              <small id="location" class="form-text text-muted">
                También puedes buscar por característica,teléfono...
              </small>
            </div>

            <div class="col-2">
              <button class="btn btn-light" type="submit"><strong>Buscar</strong></button>
            </div>
          </div>
        </form>
    </div>
    //-->
  </div>
  </div>

  </div>
</div>

  <footer class=" bg bg-light d-flex flex-column footer font-small">
    <div class="footer-copyright text-center py-3 bg-light ">
     
      <p class="text-muted">
        <b>Sobre oportunista</b>
    </p>

    <ul class="list-unstyled">
        <li><a href="{% url 'idealista_app:quienessomos' %}" class="text-info"> Quiénes somos</a></li>
    </ul>
    <a>Oportunista Copyright &copy; 2019-2019</a>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
  <script src="{% static "js/bootstrap.js" %}"></script>
</body>

</html>

{% block script %}
<script>
  var ids = ["#define", "#location", "#description", "#contact-data", "#image"]


  function redirect(that) {
    var field1ST = document.getElementById('primer').value;
    var fiell2ND = document.getElementById('segon').value;
    var fiell3RD = document.getElementById('tercer').value;
    window.location.replace("/posts" + "/" + field1ST.toLowerCase() + "/" + fiell2ND.toLowerCase() + "/" + fiell3RD.toLowerCase());

  }

</script>
{% endblock %}

templates/idealista_app/login.html
<meta charset="utf-8">
<html>

<head>
    {% load widget_tweaks %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
</head>

<body>
    <div class="vertical-center">

        <div class="container max-width-330">
            <div class="row text-center py-3">
                <img src="../../static/img/logo.svg" width="400" height="50" class="img-fluid" alt="Responsive image">
            </div>
            <div class="container col">
                <div>
                    <h2>Acceso a usuarios</h2>
                </div>
                <div>
                    <form action="/login/" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        {% if field.name != "remember" %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {% render_field field class="form-control rounded-0" %}
                            {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% endfor %}


                        <div class="form-check">
                            {% render_field form.remember class="form-check-input" %}
                            {{ form.remember.label_tag }}
                        </div>

                        <button class="btn btn-secondary btn-block rounded-0" type="submit" value="enviar">
                            Entrar en oportunista
                        </button>
                    </form>
                </div>
                <div>
                    ¿No eres usuario de oportunista? <a class="text-info"
                        href="{% url 'idealista_app:register_user' %}">Apúntate como particular</a>
                </div>
            </div>
        </div>
    </div>
</body>
<footer class=" bg bg-light d-flex flex-column footer font-small">
    <div class="footer-copyright text-center py-3 bg-light">
      <a>Oportunista Copyright &copy; 2019-2019</a>
    </div>
  </footer>
</html>

templates/idealista_app/submit.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../../static/css/style.css">

  

</head>

<body>
    <div class="vertical-center">
        <div class="container max-width-330">

            <div class="container col">
                <div class="text-center">
                    <!-- TODO hacer que funcione bien con django -->
                    <img src="../../static/img/logo.svg" class="img-fluid" alt="Responsive image">
                </div>
                <div class="alert alert-success" >
                    ¡Felicidades, tu registro se ha completado correctamente!
                </div>              
</body>

<footer class=" bg bg-light d-flex flex-column footer font-small">
    <div class="footer-copyright text-center py-3 bg-light">
      <a>Oportunista Copyright &copy; 2019-2019</a>
    </div>
  </footer>

</html>

templates/idealista_app/ver-anuncio.html
{% extends 'idealista_app/base.html' %}

{% block content %}

{% endblock %}